shortNr:
  _default:
    # support page id or hard-coded URI (detects it via is_numeric)
    notFound: "/"
    languageParentField: "l10n_parent"  # default TYPO3 field name
    languageField: "sys_language_uid" # needed for language overlay if omitted or empty = no overlay
    identifierField: "uid" # needed for language overlay if omitted or empty = no overlay

  pages: # default page
    type: page
    table: pages
    pattern: "PAGE{uid:int(min=1)}(-{sys_language_uid:int(min=0,default=0)})"
    condition: # static conditions, dynamic conditions are in the pattern
      is_event:
        contains: "test2"
        not:
          eq: 1
          contains: "test"
        #not: 1 # is_event not 1 (is_event != 1)
      score:
        gte: 50 # gte = greater than equal (score >= 5) (also supports gt)
      ranking:
        lt: 30 # lt = lower than (ranking < 30) (also supports lte)
      status: [ "active", "pending" ]    # implicit IN
      name:
        contains: "test"
      lastName:
        not:
          contains: "test"
      version:
        not:
          ends: '-rc'
        starts: 'v'
      street:
        ends: 'road'
      surname:
        isset: true # any name is ok as long the variable exists
      email:
        match: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"  # regex
      age:
        not:
          between: [ 18, 65 ]     # shorthand for >= 18 AND <= 65
      blocked_users:
        not: [ "spam", "bot" ]  # opposite of implicit IN

  myNews1:
    type: plugin
    table: tx_news_domain_model_news
    pattern: "NEWS{uid:int(min=1)}(-{sys_language_uid:int(min=0,default=0)})"
    condition: # full access to all possible conditions
      type: 0
    plugin: # plugin is mandatory for type plugin
      extension: News
      plugin: Pi1
      pid: 123
      action: detail
      controller: News
      objectName: news
